config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'pages/show'
  
  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>ようこそ</h1>
<p>トップページ</p>

app/views/home/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
        <nav>
            <% if user_signed_in? %>
                <strong><%= link_to current_user.username,pages_show_path %> </strong>
                <%= link_to 'プロフィール変更',edit_user_registration_path %>
                <%= link_to 'ログアウト',destroy_user_session_path,method: :delete %>
            <% else %>
                <%= link_to 'サインアップ',new_user_registration_path %>
                <%= link_to 'ログイン',new_user_session_path %>
            <% end %>
        </nav>
    </header>


 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>